services:
  frontend:
    build:
      context: .
      args:
        ENV: production
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - NODE_ENV=production
    env_file: .env.production
    volumes:
      - ./adorio.space.pem:/etc/ssl/adorio.space.pem:ro
      - ./adorio.space.key:/etc/ssl/adorio.space.key:ro
