services:
  frontend:
    build:
      context: .
      args:
        ENV: production
        VITE_GEMINI_API_KEY: ${VITE_GEMINI_API_KEY}
    ports:
      - "${HOST_PORT:-18080}:80"
    environment:
      CLIENT_URL: "http://localhost:${HOST_PORT:-18080}"
    env_file: .env.production