// --- DATA ---
import socialPageImage from "@/assets/socialpage.webp";

export const shelfItems = {
  web: [
    {
      id: 1,
      title: "E-Commerce Shop",
      subtitle: "Full Stack React",
      image: null,
      rating: 5.0,
      price: "Live",
      badge: "Featured",
    },
    {
      id: 2,
      title: "Portfolio V1",
      subtitle: "First Website",
      image: null,
      rating: 3.5,
      price: "Archived",
    },
    {
      id: 3,
      title: "Weather Dashboard",
      subtitle: "Data Viz",
      image: null,
      rating: 4.2,
      price: "Beta",
    },
    {
      id: 4,
      title: "Task Manager",
      subtitle: "Productivity Tool",
      image: null,
      rating: 4.8,
      price: "Live",
      badge: "Useful",
    },
    {
      id: 13,
      title: "Social",
      subtitle: "Community Feed",
      image: socialPageImage,
      rating: 5.0,
      price: "Live",
      badge: "New",
      href: "/social",
    },
  ],
  games: [
    {
      id: 5,
      title: "Cosmic Invaders",
      subtitle: "Arcade Shooter",
      image: null,
      rating: 4.5,
      price: "Playable",
      badge: "Retro",
    },
    {
      id: 6,
      title: "Dungeon Crawler",
      subtitle: "Roguelike RPG",
      image: null,
      rating: 4.0,
      price: "Demo",
    },
    {
      id: 7,
      title: "Physics Box",
      subtitle: "Matter.js Test",
      image: null,
      rating: 3.8,
      price: "Proto",
    },
    {
      id: 8,
      title: "Pixel Runner",
      subtitle: "Endless Platformer",
      image: null,
      rating: 4.1,
      price: "Playable",
    },
  ],
  art: [
    {
      id: 9,
      title: "Neon Flux",
      subtitle: "Digital Art",
      image: null,
      rating: 4.9,
      price: "Gallery",
      badge: "New",
    },
    {
      id: 10,
      title: "Cyber Prism",
      subtitle: "Illustration",
      image: null,
      rating: 5.0,
      price: "$320",
      badge: "Best Seller",
    },
    {
      id: 11,
      title: "Void Walker",
      subtitle: "Photography",
      image: null,
      rating: 4.7,
      price: "$150",
    },
    {
      id: 12,
      title: "Night Walker",
      subtitle: "Photography",
      image: null,
      rating: 4.1,
      price: "$50",
    },
  ],
};

export default shelfItems;
