// --- DATA ---

export const shelfItems = {
  web: [
    {
      id: 1,
      title: "Social",
      subtitle: "Live project",
      image:
        "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=1000&auto=format&fit=crop",
      rating: 5.0,
      price: "Live",
      badge: "Featured",
    },
    {
      id: 2,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
    {
      id: 3,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
    {
      id: 4,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
  ],
  games: [
    {
      id: 5,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
    {
      id: 6,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
    {
      id: 7,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
    {
      id: 8,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
  ],
  art: [
    {
      id: 9,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
    {
      id: 10,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
    {
      id: 11,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
    {
      id: 12,
      title: "Coming soon",
      subtitle: "project",
      image: "https://placehold.co/520x390/0f172a/fbbf24?text=Coming Soon",
      rating: 0,
      price: "Demo",
      badge: null,
    },
  ],
};

export default shelfItems;
