name: Keep Alive

on:
  schedule:
    - cron: '*/6 * * * *'  # Every 6 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Puppeteer
        run: npm install puppeteer
      - name: Run keep-alive script
        run: node keep-alive.js
