name: Keep Alive
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
concurrency:
  group: "keep-alive"
  cancel-in-progress: true
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'  # Using latest Node.js version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget curl unzip
          sudo apt install -y libx11-dev libx11-xcb1 libxcomposite1 libxrandr2 libgdk-pixbuf2.0-0 libasound2
          sudo apt install -y libnss3 libatk-bridge2.0-0 libgtk-3-0 libxss1
          sudo apt install -y libgbm-dev
          sudo apt install -y chromium-browser

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Set up Chromium path for Puppeteer
        run: |
          CHROMIUM_PATH=$(which chromium-browser)
          echo "CHROMIUM_PATH=$CHROMIUM_PATH" >> $GITHUB_ENV
          export PUPPETEER_EXECUTABLE_PATH=$CHROMIUM_PATH

      - name: Run keep-alive script
        run: |
          node keep-alive.js
